#!/usr/bin/env python1.5

# Only the supplied Python-1.5.2+ (pre-unicode tag in the Python CVS
# repository).

import sys

error_string = """
ERROR:
	Invalid Python version
	Python 1.5.2+ required
	(see pre-unicode tag in CVS repository)
"""
def exit():
	print error_string
	sys.exit()

# first, check for string methods
try:
	"ab".split()
except AttributeError:
	exit()

# check the revision string

if sys.version[:6] != '1.5.2+':
	exit()

# be sure that unicode is not present
import exceptions

if hasattr(exceptions, 'UnicodeError'):
	exit()

# be sure that the PYTHONPATH points to our modified library
try:
	exceptions.MissingFeatureError
except AttributeError:
	print """
ERROR:
	The path to the standard Python library must be
	the one supplied with the Pippy distribution.  Prepend either
	PYTHONPATH or sys.path with the correct path.
"""
	sys.exit()


if __name__ == '__main__':
	import Resourcer.resourcer
	Resourcer.resourcer.main()

