#ifndef FLOATOBJECT_C_H
#define FLOATOBJECT_C_H

#include "proto_defs.h"
static PyFloatObject *fill_free_list() SEG_FLOATOBJECT_C;
static double powu Py_PROTO((double, long)) SEG_FLOATOBJECT_C;

UNARYFUNC_PROTO(float_neg) SEG_FLOATOBJECT_C;
UNARYFUNC_PROTO(float_pos) SEG_FLOATOBJECT_C;
UNARYFUNC_PROTO(float_abs) SEG_FLOATOBJECT_C;
UNARYFUNC_PROTO(float_int) SEG_FLOATOBJECT_C;
UNARYFUNC_PROTO(float_long) SEG_FLOATOBJECT_C;
UNARYFUNC_PROTO(float_float) SEG_FLOATOBJECT_C;
BINARYFUNC_PROTO(float_add) SEG_FLOATOBJECT_C;
BINARYFUNC_PROTO(float_sub) SEG_FLOATOBJECT_C;
BINARYFUNC_PROTO(float_mul) SEG_FLOATOBJECT_C;
BINARYFUNC_PROTO(float_div) SEG_FLOATOBJECT_C;
BINARYFUNC_PROTO(float_rem) SEG_FLOATOBJECT_C;
BINARYFUNC_PROTO(float_divmod) SEG_FLOATOBJECT_C;
TERNARYFUNC_PROTO(float_pow) SEG_FLOATOBJECT_C;
INQUIRY_PROTO(float_nonzero) SEG_FLOATOBJECT_C;
COERCION_PROTO(float_coerce) SEG_FLOATOBJECT_C;
DESTRUCTOR_PROTO(float_dealloc) SEG_FLOATOBJECT_C;
PRINTFUNC_PROTO(float_print) SEG_FLOATOBJECT_C;
CMPFUNC_PROTO(float_compare) SEG_FLOATOBJECT_C;
REPRFUNC_PROTO(float_repr) SEG_FLOATOBJECT_C;
HASHFUNC_PROTO(float_hash) SEG_FLOATOBJECT_C;


#endif /* FLOATOBJECT_C_H */

