/* Function prototypes for those previously declared static */
#define UNARYFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *))
#define BINARYFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *, type *))
#define BINARYFUNC1_PROTO(name, type) static PyObject *name Py_PROTO((type *, PyObject*))
#define TERNARYFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *, type *, type *))
#define INQUIRY_PROTO(name, type) static int name Py_PROTO((type *))
#define COERCION_PROTO(name) static int name Py_PROTO((PyObject **, PyObject **))
#define INTARGFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *, int))
#define INTINTARGFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *, int, int))
#define INTOBJARGPROC_PROTO(name, type) static int name Py_PROTO((type *, int, PyObject*))
#define INTINTOBJARGPROC_PROTO(name, type) static int name Py_PROTO((type *, int, int, PyObject*))
#define OBJOBJARGPROC_PROTO(name, type) static int name Py_PROTO((type *, PyObject*, PyObject*))
#define GETREADBUFFERPROC_PROTO(name, type) static int name Py_PROTO((type *, int, void **))
#define GETWRITEBUFFERPROC_PROTO(name, type) static int name Py_PROTO((type *, int, void **))
#define GETSEGCOUNTPROC_PROTO(name, type) static int name Py_PROTO((type *, int*))
#define DESTRUCTOR_PROTO(name, type) static void name Py_PROTO((type *))
#define PRINTFUNC_PROTO(name, type) static int name Py_PROTO((type *, FILE *, int))
#define GETATTRFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *, char *))
#define GETATTROFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *, PyObject*))
#define SETATTRFUNC_PROTO(name, type) static int name Py_PROTO((type *, char *, PyObject*))
#define SETATTROFUNC_PROTO(name, type) static int name Py_PROTO((type *, PyObject*, PyObject*))
#define CMPFUNC_PROTO(name, type) static int name Py_PROTO((type *, type *))
#define REPRFUNC_PROTO(name, type) static PyObject *name Py_PROTO((type *))
#define HASHFUNC_PROTO(name, type) static long name Py_PROTO((type *))
#define PYCFUNCTION_PROTO(name, type) static PyObject *name Py_PROTO((type *, type *))
